<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  
  <title>Freecad Python Scripting | Blog of James Brown</title>
  <meta name="author" content="James Brown">
  
  <meta name="description" content="This article provides an explanation of FreeCAD scripting, specifically focusing on how to manipulate objects and create circles within specified bounds using Python. The article includes examples of defining dimensions and the number of circles needed, as well as calculating side lengths and margins to generate squares with given parameters.">
  
  
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <meta property="og:title" content="Freecad Python Scripting"/>
  <meta property="og:site_name" content="Blog of James Brown"/>

  
    <meta property="og:image" content=""/>
  

  
    <link rel="alternative" href="/blog/atom.xml" title="Blog of James Brown" type="application/atom+xml">
  
  
    <link href="/blog/favicon.png" rel="icon">
  

  <!-- CSS -->
  <link rel="stylesheet" href="/blog/css/themes/cerulean.css" media="screen" type="text/css">
  <link rel="stylesheet" href="/blog/css/font-awesome.css" media="screen" type="text/css">
  <link rel="stylesheet" href="/blog/css/style.css" media="screen" type="text/css">
  <link rel="stylesheet" href="/blog/css/responsive.css" media="screen" type="text/css">
  <link rel="stylesheet" href="/blog/css/highlight.css" media="screen" type="text/css">
  <link rel="stylesheet" href="/blog/css/highlight-default.min.css" media="screen" type="text/css">
  <link rel="stylesheet" href="/blog/css/google-fonts.css" media="screen" type="text/css">
  <link rel="stylesheet" href="/blog/css/comment.css" media="screen" type="text/css">
  <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.9/es5-shim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-sham.min.js"></script>
  <![endif]-->

  <script src="/blog/js/jquery-2.0.3.min.js"></script>
  
  
  <!-- analytics -->
  



<meta name="generator" content="Hexo 7.0.0"></head>

<body>
  <nav id="main-nav" class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <button type="button" class="navbar-header navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	<span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand" href="/blog/">Blog of James Brown</a>
      <div class="collapse navbar-collapse nav-menu">
		<ul class="nav navbar-nav">
		  
		  <li>
			<a href="/blog/archives" title="All the articles.">
			  <i class="fa fa-archive"></i>Archives
			</a>
		  </li>
		  
		  <li>
			<a href="/blog/categories" title="All the categories.">
			  <i class="fa fa-folder"></i>Categories
			</a>
		  </li>
		  
		  <li>
			<a href="/blog/tags" title="All the tags.">
			  <i class="fa fa-tags"></i>Tags
			</a>
		  </li>
		  
		  <li>
			<a href="/blog/about" title="About me.">
			  <i class="fa fa-user"></i>About
			</a>
		  </li>
		  
		</ul>
      </div>
    </div> <!-- container -->
</nav>
<div class="clearfix"></div>

  <div class="container">
    <div class="content">
      


	
		<div class="page-header page-header-inverse ">		
			<h1 class="title title-inverse "> Freecad Python Scripting</h1>
		</div>		
	






<div class="row post">
	<!-- cols -->
	
	<div id="top_meta"></div>
	<div class="col-md-9">
	

	<!-- content -->
	<div class="mypage">		
	  
		 <div class="alert alert-success description">
			<i class="fa fa-info-circle"></i> <p>This article provides an explanation of FreeCAD scripting, specifically focusing on how to manipulate objects and create circles within specified bounds using Python. The article includes examples of defining dimensions and the number of circles needed, as well as calculating side lengths and margins to generate squares with given parameters.</p>
			
		 </div> <!-- alert -->
	  		

	  <p>Reference:</p>
<p><a target="_blank" rel="noopener" href="https://wiki.freecad.org/FreeCAD_Scripting_Basics">https://wiki.freecad.org/FreeCAD_Scripting_Basics</a></p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> Part</span><br><span class="line">doc = FreeCAD.ActiveDocument</span><br><span class="line"><span class="comment"># list all objects</span></span><br><span class="line">all_objects = doc.Objects</span><br><span class="line"><span class="comment"># list all names</span></span><br><span class="line">all_object_names = [it.Name <span class="keyword">for</span> it <span class="keyword">in</span> all_objects]</span><br><span class="line"><span class="comment"># get object by name</span></span><br><span class="line">obj = doc.getObject(<span class="string">&quot;myObjectName&quot;</span>)</span><br><span class="line"><span class="comment"># get vertex point</span></span><br><span class="line">vertex_point = obj.Shape.Vertexes[<span class="number">0</span>].Point</span><br><span class="line"><span class="comment"># create new line</span></span><br><span class="line">new_line = Part.makeLine((-<span class="number">200</span>, -<span class="number">200</span>, <span class="number">0</span>), (<span class="number">200</span>, <span class="number">200</span>, <span class="number">0</span>))</span><br><span class="line"><span class="comment"># insert the line</span></span><br><span class="line">Part.show(new_line)</span><br><span class="line"><span class="comment"># recompute the document</span></span><br><span class="line">doc.recompute()</span><br><span class="line"></span><br></pre></td></tr></table></figure>

<p>Draw squares within specific bounds:</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br></pre></td><td class="code"><pre><span class="line">margin = <span class="number">15</span></span><br><span class="line"><span class="comment"># Define the dimensions of the square area</span></span><br><span class="line">x_min = -<span class="number">210.134</span> + margin</span><br><span class="line">x_max = -<span class="number">84.134</span> - margin</span><br><span class="line">y_min = -<span class="number">140.0997</span> + margin</span><br><span class="line">y_max = -<span class="number">14.0997</span> - margin</span><br><span class="line">z = <span class="number">0</span></span><br><span class="line"><span class="comment"># Define the number of squares in each row and column</span></span><br><span class="line">num_squares = <span class="number">10</span></span><br><span class="line"><span class="comment"># Calculate the side length of each square</span></span><br><span class="line">x_length = (x_max - x_min) / num_squares</span><br><span class="line">y_length = (y_max - y_min) / num_squares</span><br><span class="line">margin_portion = <span class="number">0.17</span></span><br><span class="line">hole_portion = <span class="number">1</span> - <span class="number">2</span> * margin_portion</span><br><span class="line"><span class="comment"># Create the squares</span></span><br><span class="line"><span class="keyword">for</span> i <span class="keyword">in</span> <span class="built_in">range</span>(num_squares):</span><br><span class="line"><span class="keyword">for</span> j <span class="keyword">in</span> <span class="built_in">range</span>(num_squares):</span><br><span class="line">x_start = x_min + i * x_length + x_length * margin_portion</span><br><span class="line">y_start = y_min + j * y_length + y_length * margin_portion</span><br><span class="line">square_points = [</span><br><span class="line">(x_start, y_start, z),</span><br><span class="line">(x_start + x_length * hole_portion, y_start, z),</span><br><span class="line">(x_start + x_length * hole_portion, y_start + y_length * hole_portion, z),</span><br><span class="line">(x_start, y_start + y_length * hole_portion, z),</span><br><span class="line">(x_start, y_start, z), <span class="comment"># to make it closed</span></span><br><span class="line">]</span><br><span class="line">square = Part.makePolygon(square_points)</span><br><span class="line">Part.show(square)</span><br><span class="line"></span><br></pre></td></tr></table></figure>

<p>Draw circles with specific bounds:</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line">margin = <span class="number">15</span></span><br><span class="line"><span class="comment"># Define the dimensions of the square area</span></span><br><span class="line">x_min = -<span class="number">210.134</span> + margin</span><br><span class="line">x_max = -<span class="number">84.134</span> - margin</span><br><span class="line">y_min = -<span class="number">140.0997</span> + margin</span><br><span class="line">y_max = -<span class="number">14.0997</span> - margin</span><br><span class="line">z = <span class="number">0</span></span><br><span class="line"><span class="comment"># Define the number of circles in each row and column</span></span><br><span class="line">num_circles = <span class="number">10</span></span><br><span class="line"><span class="comment"># Calculate the side length of each circle</span></span><br><span class="line">x_length = (x_max - x_min) / num_circles</span><br><span class="line">y_length = (y_max - y_min) / num_circles</span><br><span class="line">margin_portion = <span class="number">0.17</span></span><br><span class="line">radius_portion = <span class="number">0.5</span> - margin_portion</span><br><span class="line">radius = x_length * radius_portion</span><br><span class="line">direction = App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>)</span><br><span class="line"><span class="comment"># Create the squares</span></span><br><span class="line"><span class="keyword">for</span> i <span class="keyword">in</span> <span class="built_in">range</span>(num_circles):</span><br><span class="line"><span class="keyword">for</span> j <span class="keyword">in</span> <span class="built_in">range</span>(num_circles):</span><br><span class="line">x_center = x_min + i * x_length + x_length * <span class="number">0.5</span></span><br><span class="line">y_center = y_min + j * y_length + y_length * <span class="number">0.5</span></span><br><span class="line">circle = Part.makeCircle(radius, App.Vector(x_center, y_center, <span class="number">0</span>), direction)</span><br><span class="line">Part.show(circle)</span><br><span class="line"></span><br></pre></td></tr></table></figure>
	  
	</div>

	<!-- recommended posts -->
	

	<div>
  	<center>
	<div class="pagination">
<ul class="pagination">
	 
				
		<li class="prev"><a href="/blog/2024/05/13/c7b67e49-4354-4222-9c59-c30a68311793/" class="alignleft prev"><i class="fa fa-arrow-circle-o-left"></i>Prev</a></li>
  		

        <li><a href="/blog/archives"><i class="fa fa-archive"></i>Archive</a></li>

		
          <li class="next"><a href="/blog/2024/05/12/8488cce3-4170-4d90-bc4a-ab700a07bd2e/" class="alignright next">Next<i class="fa fa-arrow-circle-o-right"></i></a></li>
        
	
</ul>
</div>

    </center>
	</div>

    <!-- share -->
    
        
    <div class="bdsharebuttonbox">
        <a href="#" class="bds_more" data-cmd="more"></a>
        <a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
        <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
        <a href="#" class="bds_fbook" data-cmd="fbook" title="分享到Facebook"></a>
        <a href="#" class="bds_twi" data-cmd="twi" title="分享到Twitter"></a>
        <a href="#" class="bds_linkedin" data-cmd="linkedin" title="分享到linkedin"></a>
        <a href="#" class="bds_evernotecn" data-cmd="evernotecn" title="分享到印象笔记"></a>
        <a href="#" class="bds_youdao" data-cmd="youdao" title="分享到有道云笔记"></a>
        <a href="#" class="bds_copy" data-cmd="copy" title="分享到复制网址"></a>
    </div>
    <script>
        window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"24"},"share":{}};
        with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
    </script>


        

    
	
	<!-- comment -->
	
<section id="comment">
  <h2 class="title">Comments</h2>
  
</section>


	</div> <!-- col-md-9/col-md-12 -->
		
	
	<div id="side_meta">
		<div class="col-md-3" id="post_meta"> 

	<!-- date -->
	
	<div class="meta-widget">
	<i class="fa fa-clock-o"></i>
	2024-05-13 
	</div>
	

	<!-- categories -->
    
	<div class="meta-widget">
	<a data-toggle="collapse" data-target="#categorys"><i class="fa fa-folder"></i></a>	
    <ul id="categorys" class="tag_box list-unstyled collapse in">
          
  <li>
    <li><a href="/blog/categories/Python/">Python<span>6</span></a></li>
  </li>

    </ul>
	</div>
	

	<!-- tags -->
	
	<div class="meta-widget">
	<a data-toggle="collapse" data-target="#tags"><i class="fa fa-tags"></i></a>		  
    <ul id="tags" class="tag_box list-unstyled collapse in">	  
	    
  <li><a href="/blog/tags/Python/">Python<span>25</span></a></li> <li><a href="/blog/tags/FreeCAD/">FreeCAD<span>2</span></a></li> <li><a href="/blog/tags/scripting/">scripting<span>1</span></a></li> <li><a href="/blog/tags/object-manipulation/">object manipulation<span>1</span></a></li> <li><a href="/blog/tags/circles/">circles<span>1</span></a></li> <li><a href="/blog/tags/bounds/">bounds<span>1</span></a></li> <li><a href="/blog/tags/dimensions/">dimensions<span>1</span></a></li>

    </ul>
	</div>
	

	<!-- toc -->
	<div class="meta-widget">
	
	</div>
	
    <hr>
	
</div><!-- col-md-3 -->

	</div>
		

</div><!-- row -->




    </div>
  </div>
  <div class="container-narrow">
    <footer> <p>
  &copy; 2024 James Brown
  
      with help from <a href="http://hexo.io/" target="_blank">Hexo</a> and <a href="http://getbootstrap.com/" target="_blank">Twitter Bootstrap</a>. Theme by <a target="_blank" rel="noopener" href="http://github.com/wzpan/hexo-theme-freemind/">Freemind</a>.    
</p> </footer>
  </div> <!-- container-narrow -->
  


  
<a id="gotop" href="#">   
  <span>▲</span> 
</a>

<script src="/blog/js/jquery.imagesloaded.min.js"></script>
<script src="/blog/js/gallery.js"></script>
<script src="/blog/js/bootstrap.min.js"></script>
<script src="/blog/js/main.js"></script>
<script src="/blog/js/search.js"></script> 


<link rel="stylesheet" href="/blog/fancybox/jquery.fancybox.css" media="screen" type="text/css">
<script src="/blog/fancybox/jquery.fancybox.pack.js"></script>
<script type="text/javascript">
(function($){
  $('.fancybox').fancybox();
})(jQuery);
</script>



   <script type="text/javascript">      
     var search_path = "search.xml";
	 if (search_path.length == 0) {
	 	search_path = "search.xml";
	 }
	 var path = "/blog/" + search_path;
     searchFunc(path, 'local-search-input', 'local-search-result');
   </script>


<!-- syntax highlighting -->


</body>
</html>